### ISSUE TITLE
CI/CD example

### ISSUE THREAD

**Issue by eduherminio** [IntarBV/dotnet-maui-android#3]
Can you point us to an example of how to use the image in the CI/CD context it's designed for?

**Comment by Ghostbird** [comment]
The goal of the resulting image is that you can run `dotnet build -restore` on a MAUI Android workspace without first needing to install additional _software_.

I recommend you try this out by building and running the docker image on your local machine and use that to figure out what you need to do in your CI/CD pipeline to achieve that.

The basics should be:

- Get the source code you want to build
- `dotnet build`

If you're going to deploy to e.g. Google Play store and you want a valid signed build, add an intermediate step that loads the necessary secrets. This depends on your setup but in our case the minimum we need to set are the values for the environment variables:
  - `AndroidSigningStorePass`
  - `AndroidSigningKeyPass`
  - `AndroidSigningKeyStore`
  - `AndroidSigningKeyAlias`

This should build an AAB file, which you can then upload somewhere for further processing (e.g. deploy to Google Play Store, F-Droid, etc.).

## Minimal example of steps in Github Actions

Note: This example adds one additional step to read the keystore from the Github environment secrets. This is because github secrets are limited to text, yet the keystore is a binary file. Therefore the keystore binary has been base64 encoded and added to Github secrets. It is then base64 decoded and written to `upload.keystore` in the step before the build.

```yaml
steps:
  - name: Checkout
    uses: actions/checkout@master
  - name: Write keystore file from secrets
    shell: bash
    run: |
      base64 -d > "upload.keystore" <<< "${{ secrets.AndroidSigningKeyStore }}"
  - name: Build
    shell: bash
    env:
      Configuration: Release
      AndroidSigningStorePass: ${{ secrets.AndroidSigningStorePass }}
      AndroidSigningKeyPass: ${{ secrets.AndroidSigningKeyPass }}
      AndroidSigningKeyStore: upload.keystore
      AndroidSigningKeyAlias: ${{ vars.AndroidSigningKeyAlias }}
    run: dotnet build -restore
  - name: Upload AAB
    uses: actions/upload-artifact@v4
    with:
      name: aab
      path: bin/Release/net9.0-android/com.example.app-Signed.aab
      if-no-files-found: error
      retention-days: 1

**Comment by dos-ise** [comment]
Great work, i use ths in gitlab like this:

```
dotnet_maui_apk_publish:
   stage: publish
   image: /docker-hub/conneqthub/dotnet-maui-android:latest
   script: 
     - cd Viewer.MAUI/Viewer.Maui/
     - dotnet publish -f:net9.0-android -c:Demo_Android /p:ArchiveOnBuild=true
   when: manual
   dependencies:
    - dotnet_maui_build
   artifacts:
    paths:
      - ./**/*.apk
    expire_in: 4 week  
```
